USE RSH
GO

ALTER TABLE RSH_BASE
ADD tipohoga INT NULL
GO

UPDATE RSH_BASE
SET RSH_BASE.tipohoga = pariente.tipohoga
FROM
(SELECT formulario, CASE
	WHEN JEFE=1 AND CONYUGE=0 AND HIJO_SOLTERO=0 AND LESS_10=0 AND HIJO_CASADO=0 AND OTRO_PARIENTE=0 AND
		 NO_PARIENTE=0 AND EMPLEADO_DOMESTICO=0 THEN 1
	WHEN JEFE=1 AND CONYUGE=1 AND HIJO_CASADO=0 AND OTRO_PARIENTE=0 AND
		 NO_PARIENTE=0 THEN 2
	WHEN JEFE=1 AND CONYUGE=0 AND (HIJO_SOLTERO=1 OR LESS_10=1) AND HIJO_CASADO=0 AND OTRO_PARIENTE=0 AND
		 NO_PARIENTE=0 THEN 3
	WHEN (JEFE=1 AND NO_PARIENTE=1) OR (JEFE=1 AND CONYUGE=0 AND HIJO_SOLTERO=0 AND LESS_10=0 AND HIJO_CASADO=0 AND
		OTRO_PARIENTE=0 AND NO_PARIENTE=0 AND EMPLEADO_DOMESTICO=1) THEN 5
	WHEN JEFE=1 AND (HIJO_CASADO=1 OR OTRO_PARIENTE=1) THEN 4
    END AS tipohoga
FROM (SELECT formulario,
	MAX(CASE WHEN p04=1 THEN 1 ELSE 0 END) JEFE,
	MAX(CASE WHEN p04=2 THEN 1 ELSE 0 END) CONYUGE,
	MAX(CASE WHEN p04 = 3 AND p11 = 5 THEN 1 ELSE 0 END) HIJO_SOLTERO,
	SUM(CASE WHEN p09<10 THEN 1 ELSE 0 END) LESS_10,
	MAX(CASE WHEN p04=3 AND (p11=1 OR p11=2 OR p11=3 OR p11=4 OR p11=6) THEN 1 ELSE 0 END) HIJO_CASADO,
	MAX(CASE WHEN p04=4 OR p04=5 OR p04=6 OR p04=7 OR p04=8 OR p04=9 THEN 1 ELSE 0 END) OTRO_PARIENTE,
	MAX(CASE WHEN p04=10 THEN 1 ELSE 0 END) NO_PARIENTE,
	MAX(CASE WHEN p04=11 OR p04=12 THEN 1 ELSE 0 END) EMPLEADO_DOMESTICO
	FROM RSH_BASE
	GROUP BY formulario) aux) pariente
	WHERE RSH_BASE.formulario = pariente.formulario
	GO

